---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# indirectfacilitation

The goal of indirectfacilitation is to ...

## Installation

You can install indirectfacilitation from github with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
#devtools::install_github("alaindanet/indirect_facilitation_model")
```

## Example

This is a basic example which shows you how to solve a common problem:


- Load the packages:

```{r}
library(simecol)
library(ggplot2)
library(tibble)
library(magrittr)
devtools::load_all()

```

- Load the model and specify the parameters:

```{r}
mod <- indirect_facilitation_model()
init(mod)
parms(mod)["g"] <- 0.2
parms(mod)[c("gamma1", "u")] <- c(0.1, 1)
parms(mod)["protection_type"] <- list("first_protect")
times(mod) <- c(from = 0, to = 3000, by = 1)
solver(mod) <- steady_state_3
```

- Launch a simulation and plot the result:

```{r}
mod_run <- sim(mod)
tail(out(mod_run), 10)
plotnp(mod_run)
```

### Gradient

```{r}
gradient <- list(
  g = seq(0, 0.3, length.out = 5), # Grazing
  b = seq(1, 0.5, length.out = 5) # Environmental quality
  )

options(mc.cores = 3)
gradient_2d <- run_scenarii_gradient(
  gradient = gradient,
  model_spec = "two_facilitation_model",
  param = c(protection_type = list("first_protect"), gamma1 = 0.1, u = 0),
  scenarii = init_scenarii(
       type = "together", model = two_facilitation_model(),
       ini_cover = .8),
  time_seq = c(from = 0, to = 3000, by = 1),
  set_tail = 10,
  solver_type = steady_state_4
  )

averaged_runs <- avg_runs(gradient_2d, cut_row = 10)
plot_diagram(averaged_runs, param = c(x = "b", y = "g"))
```


