---
title: "Appendix"
author: "Alain Danet"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Appendix}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(tidyverse)
library(cowplot)
library(simecol)
library(magrittr)
library(directlabels)
devtools::load_all()

knitr::opts_chunk$set(
  echo = FALSE,
  fig.dim = c(10, 7) #width, height
  )
cowplot_theme <- theme_get()
theme_set(cowplot_theme)
theme_update(axis.title = element_text(size = 8))
```

# Pair approximation cooccurrences

## Relating to grazing and aridity

```{r, eval = FALSE}

#filtered_scenar <- filter(u0_5, scenario == "together"); 
#filtered_scenar$run %<>%
  #mutate(
    #N = ifelse(N < .05 & N != 0, NA, N),
    #P = ifelse(P < .05 & P != 0, NA, P)
    #)

#occurenres <- compute_occurences(filtered_scenar) 

#p <- plot_fig3bisbis(occurenres)
#p
#ggplot2::ggsave(paste(dd, "clustering_pa_tot.pdf", sep = ""), p, width = 24, height = 18, units = "cm", device = cairo_pdf)

```

## Relating to dispersal and indirect facilitation strength


```{r}
rm(list = ls())
data(clust_pa)

clust_pa$run %<>%
  mutate(
    g = 0.2, #dummy variable for plot_fig3bisbis
    N = ifelse(N < .0001 & N != 0, 0, N),
    P = ifelse(P < .0001 & P != 0, 0, P)
    )

occurenres <- compute_occurences(clust_pa) 

a <- plot_fig3bisbis(occurenres, x = "del", y = "u", facet = "g")
c1 <- plot_diagram(occurenres , param = c(x = "del", y = "u"), fill = "cveg")
e <- plot_diagram(compute_states(clust_pa), param = c(x = "del", y = "u"))

```

## Relating to dispersal and direct facilitation

```{r disp and facilitation, fig.dim = c(10, 4)}
load("../inst/direct_facilitation_effect_pa_avg.RData")
clust_avg <- scenar_avg
clust_avg$run %<>%
  mutate(
    g = 0.2, #dummy variable for plot_fig3bisbis
    N = ifelse(N < .01 & N != 0, 0, N),
    P = ifelse(P < .01 & P != 0, 0, P)
    )

occurences <- compute_occurences(clust_avg) 
filter(occurences$run, is.infinite(100))
summary(occurences$run$cveg)

a <- plot_fig3bisbis(occurences, x = "del", y = "f", facet = "g") +
  xylabs(x = "del", y = "f") + theme_alain()
b <- plot_diagram(compute_states(clust_avg), param = c(x = "del", y = "f")) +
  xylabs(x = "del", y = "f") + theme_alain()
c1 <- plot_diagram(occurences, param = c(x = "del", y = "f"), fill = "cveg") +
  xylabs(x = "del", y = "f") + theme_alain()

cowplot::plot_grid(a, b, c1, labels = "AUTO", ncol = 1)
```

# Appendix

## Relating to aridity and direct facilitation

```{r aridity and facilitation, fig.dim = c(10, 4)}

load("../inst/f_b_effect_pa_avg.RData")
clust_avg <- scenar_avg

clust_avg$run %<>%
  mutate(
    g = 0.2, #dummy variable for plot_fig3bisbis
    N = ifelse(N < .01 & N != 0, 0, N),
    P = ifelse(P < .01 & P != 0, 0, P)
    )

occurences <- compute_occurences(clust_avg) 
filter(occurences$run, is.infinite(cveg))
summary(occurences$run$cveg)

a <- plot_fig3bisbis(occurences, x = "b", y = "f", facet = "g") +
  xylabs(x = "b", y = "f") + theme_alain()
b <- plot_diagram(compute_states(clust_avg), param = c(x = "b", y = "f")) +
  xylabs(x = "b", y = "f") + theme_alain()
c1 <- plot_diagram(occurences, param = c(x = "b", y = "f"), fill = "cveg") +
  xylabs(x = "b", y = "f") + theme_alain()

cowplot::plot_grid(a, c1, b, labels = "AUTO", ncol = 3)
```

## Relating to aridity and indirect facilitation

```{r aridity and indirect facilitation, fig.dim = c(10, 4)}

load("../inst/u_b_effect_pa_avg.RData")
clust_avg <- scenar_avg

clust_avg$run %<>%
  mutate(
    g = 0.2, #dummy variable for plot_fig3bisbis
    N = ifelse(N < .01 & N != 0, 0, N),
    P = ifelse(P < .01 & P != 0, 0, P)
    )

occurences <- compute_occurences(clust_avg) 
filter(occurences$run, is.infinite(cveg))
summary(occurences$run$cveg)

a <- plot_fig3bisbis(occurences, x = "b", y = "u", facet = "g") +
  xylabs(x = "b", y = "u") + theme_alain() 
b <- plot_diagram(compute_states(clust_avg), param = c(x = "b", y = "u")) +
  xylabs(x = "b", y = "u") + theme_alain()
c1 <- plot_diagram(occurences, param = c(x = "b", y = "u"), fill = "cveg") +
  xylabs(x = "b", y = "u") + theme_alain()

cowplot::plot_grid(a, c1, b, labels = "AUTO", ncol = 3)
```

## Consistence pair approximation and cellular automata

```{r}
# Plot final densities along gradients 

model_type <- c("ca", "pa")
simulation <- list()
for (i in seq_along(model_type)) {
  load(file = paste("../inst/clustering_", model_type[i], "_avg.RData", sep = ""))
  scenar_avg$run %<>% mutate( model = factor(model_type[i], levels = model_type))

  if (model_type[i] == "ca") {
  scenar_avg$run %<>% gather(rho, value, N, P) %>%
  group_by(scenario, u, del, rho, model) %>%
  summarise(value = mean(value, na.rm = TRUE)) %>%
  spread(rho, value)
  }

  simulation[[i]] <- select(scenar_avg$run, scenario, u, del, N, P, model)
  rm(scenar_avg)
}
simulation %<>% bind_rows(simulation)

load(file = paste("../inst/clustering_", model_type[i], "_avg.RData", sep = ""))
scenar_avg$run <- ungroup(simulation) %>%  ##NOT SAFE
  select(-scenario)
scenar_avg$run %<>% gather(rho, value, N, P) %>% 
  group_by(u, del, rho, model) %>%
  mutate(ind = row_number()) %>%
  spread(model, value) %>%
  ungroup() %>% select(-ind) %>%
  mutate(
    ca = ifelse(ca < .01, 0, ca),
    pa = ifelse(pa < .01, 0, pa),
    diff_ca_pa = (ca - pa) / pa# * 100
    )

ca <- plot_diagram(scenar_avg, param = c(x = "del", y = "u"), fill = "diff_ca_pa") + 
  theme_alain() +
  scale_fill_temperature() +
  facet_grid(cols = vars(rho), labeller = species_labeller()) +
  xylabs(x = "del", y = "u") +
  labs(fill = "Diff") +
  geom_point(aes(x = .1, y = 5), color = "red") +
  geom_point(aes(x = .1, y = 0), color = "red")
ca

cowplot::save_plot("~/Documents/thesis/papers/indirect_facilitation_dryland_stability/fig/density_ca_pa.pdf",
  ca,
  base_width = 4.3,
  base_height = 3.8,
  ncol = 2)

## Diff to write in the paper:
filter(scenar_avg$run, u == 5) %>% select(diff_ca_pa) %>% max(.)

```
