---
title: "Main results"
author: "Alain Danet"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Main results}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE}
library(tidyverse)
library(cowplot)
library(simecol)
library(magrittr)
library(directlabels)
devtools::load_all()

dd <- "~/Documents/thesis/talks/coffee_chat/fig"

knitr::opts_chunk$set(
  echo = FALSE,
  fig.dim = c(10, 7) #width, height
  )
cowplot_theme <- theme_get()
theme_set(cowplot_theme)
theme_update(axis.title = element_text(size = 8))
```
```{r export bib citation}
export_citation <- function(pkg_name = NULL, dir_name = NULL){
  x <- toBibtex(citation(pkg_name))
  cat(x, file = paste(dir_name, pkg_name, ".bib", sep = ""), sep = "\n") 
}
sapply(c("simecol", "deSolve"), export_citation, dir_name = "~/Téléchargements/")
```


# Model definition 

```{r, fig.width = 7, fig.height = 5, echo = FALSE}
compute_p_one_z <- function(gamma1, u) {
 1 - exp(- u * gamma1)
}

factors <- list(
  gamma1 = seq(0, .2, .01),
  u = c(0, 5, 10) 
  )

df <- expand.grid(factors) 
df %<>% 
  dplyr::mutate(
  tau = purrr::pmap_dbl(list(gamma1, u), compute_p_one_z),
  u = as.factor(u),
  )

#Plot
p1 <- ggplot(df, aes(x = gamma1, y = tau)) +
  geom_line(aes(colour = u)) +
  labs(
    y = expression(paste("Grazing protection (", p[frac(1,z)], ")")), 
    x = expression(paste("Cost of defense (", gamma, ")"))) +
  ylim(0,1) +
  theme_alain() +
  theme(legend.position="bottom") 
p2 <- ggdraw() +
  draw_image(magick::image_read_svg("~/Documents/thesis/papers/indirect_facilitation_dryland_stability/fig/stand_alone.svg"))

```

```{r ca and pa time series}
mod_list <- list(
  pa = two_facilitation_model(),
  ca = ca_two_facilitation_model()
  )
set.seed(123)
output <- lapply(mod_list, function(x){
  times(x) <- c(from = 0, to = 3000, by = 1)
  parms(x) <- parms(two_facilitation_model())
  parms(x)[c("b", "g")] <- c(1, .13)
  simul <- sim(x)
  # Is it PA or CA?
  mod_type <- ifelse("PD" %in% names(out(simul)), "pa", "ca")
  #common output
  out(simul) %>% select(time, N, P, D) %>%
    mutate(model = mod_type) %>%
    as.tibble()
    })
example_time_series <- do.call(rbind, output) %>%
  mutate(model = as.factor(model),
    total = N + P) %>%
  select(-D) %>%
  gather(species, rho, N, P, total)

p_ts <- ggplot(example_time_series, aes(x = time, y = rho)) +
  geom_line(aes(color = species, linetype = model)) +
  scale_colour_species() +
  scale_linetype_model() +
  xylabs(x = "time", y = "rho") +
  ylim(0, 1) +
  theme_alain()
  #theme(legend.position="bottom")
p_ts

```

```{r plot fig1}
model_fig <- plot_grid(p2, p1,  labels = "AUTO", rel_heights = c(1, 1), rel_widths = c(1.5, 1), ncol = 2)
fig1 <- plot_grid(model_fig, p_ts, nrow = 2, labels = c('', 'C'))

save_plot("~/Documents/thesis/papers/indirect_facilitation_dryland_stability/fig/model.pdf",
  fig1,
  base_width = 129/25.4,
  base_height = 64/25.4,
  nrow = 2)
# 39 mm, 84 mm, 129 mm, or 174 mm wide and not higher than 234 mm
```


# Stability 

```{r, echo = FALSE}

data(u0_5)

protegee_only <- filter(u0_5, !(scenario %in% c("together", "low_together")))
protegee_only$inits <- protegee_only$inits[c("protegee_only", "low_protegee_only")]
u0_5 %<>% filter(scenario %in% c("together", "low_together"))
u0_5$inits <- u0_5$inits[c("together", "low_together")]

states <- compute_states(u0_5, type = "double")

fig2 <- plot_fig2(states) + theme_alain() + theme(legend.position = "bottom") +
  guides(
    fill = guide_legend(nrow = 3, title.position = "top")
    )
legend_fig2 <- get_legend(fig2)
fig2 <- fig2 + theme(legend.position = "none") 

final_fig_2 <- plot_grid(
  fig2,
  legend_fig2,
  rel_heights = c(1, 0.5),
  nrow = 2
)
final_fig_2

#"~/Documents/thesis/papers/indirect_facilitation_dryland_stability/fig/Stability.pdf"
#1 inches to mm = 25.4 mm
cowplot::save_plot("~/Documents/thesis/papers/indirect_facilitation_dryland_stability/fig/stability.pdf",
  final_fig_2,
  base_width = 118/25.4,
  base_height = 3.5,
  ncol = 1, nrow = 1)

```

```{r}
letter_pos <- c(x = .49, y = .95)
g_val <- c(0, .1, .25, .3)
u_val <- c(0, 5)
bifurc_together <- filter(u0_5, g %in% g_val, u %in% u_val)
margin_set_up <- margin(t = 10, r = 0, b = 2, l = 2, unit = "pt")

fig3 <- plot_bifurcation(bifurc_together, N, P) +
    ggplot2::scale_colour_manual(
      name = "Species",
      values = c(N = "#BBCC33", P = "#99DDFF"),
      labels = species_labeller()
      ) +
    facet_grid(rows = vars(g), cols = vars(u), labeller =  labeller(u = u_labeller, g = facet_labeller(prefix = "g"))) +
    xylabs(x = "b", y = "rho") +
    theme_alain() +
    theme(
      legend.position = "none",
      strip.text.y = element_blank(),
      axis.title.x = element_text(hjust = 0.9),
      plot.background = element_rect(color = "black", linetype = 0)
      ) +
    ggtitle("Protegee and Nurse")
## Put A, B, C
combination_facet_var <- expand.grid(
  u = bifurc_together$run$u %>% unique,
  g = bifurc_together$run$g %>% unique
)
letter_left_panel <- tibble(
  g = combination_facet_var$g,
  u = combination_facet_var$u,
  x = letter_pos["x"],
  y = letter_pos["y"],
  lab = c("A", "B", "D", "E", "G", "H", "J", "K")
  )
left_panel <- fig3 +
  geom_text(aes(x = x, y = y, label = lab, group = NULL),
    data = letter_left_panel,
    inherit.aes = FALSE)
    
#################
#  right panel  #
#################

protegee_only %<>% filter(u == 0, g %in% g_val) %>%
select(P)

right_panel <- plot_bifurcation(protegee_only, P) +
    ggplot2::scale_colour_manual(
      name = "Species",
      values = c(N = "#BBCC33", P = "#99DDFF"),
      labels = species_labeller()
      ) +
    facet_grid(rows = vars(g), cols = vars(u), labeller = labeller(u = u_labeller, g = facet_labeller(prefix = "g"))) +
    xylabs(y = "rho") +
    xlab("") +
    theme_alain() +
    theme(legend.position = "none", 
      axis.text.y = element_blank(),
      axis.title.y = element_blank(),
      axis.title.x = element_text(hjust = 0.1),
      plot.background = element_rect(color = "black", linetype = c(1))
      ) +
    ggtitle("Protegee alone")
## Put A, B, C
letter_right_panel <- tibble(
  g = protegee_only$run$g %>% unique,
  u = protegee_only$run$u %>% unique,
  x = letter_pos["x"],
  y = letter_pos["y"],
  lab = c("C", "F", "I", "L")
  )
right_panel <- right_panel +
  geom_text(aes(x = x, y = y, label = lab, group = NULL),
    data = letter_right_panel,
    inherit.aes = FALSE)

legend_b <- cowplot::get_legend(left_panel + theme(legend.position="bottom"))

top_row <- cowplot::plot_grid(left_panel, right_panel, rel_widths = c(1, .55))
bifurcation <- cowplot::plot_grid(top_row, legend_b, nrow = 2, rel_heights = c(1,.05))
bifurcation

#1 inches to mm = 25.4 mm
cowplot::save_plot("~/Documents/thesis/papers/indirect_facilitation_dryland_stability/fig/bifurcation.pdf",
  bifurcation,
  base_width = 174/25.4,
  base_height = 4.3,
  ncol = 1)
```

# Cooccurrences in cellular automata

## Relating to dispersal and indirect facilitation strength

```{r prepare data}
data(clust_ca)

##Options 
rho_threshold <- .01

##
clust_ca$run <- tibble::as.tibble(clust_ca$run) 
clust_ca$run <- arrange(clust_ca$run, u, del, rep)
occurences <- clust_ca

# Which simulation is good 
consistence <- occurences$run %>%
  group_by(u, del) %>%
  nest() %>%
  mutate(consistence = map_lgl(data, check_consistency, threshold = rho_threshold))

# Keep the good values
filtered_scenar <- occurences; 
filtered_scenar$run <- unnest(consistence) 
filtered_scenar$run %<>%
  mutate(
    N = ifelse(N < rho_threshold & N != 0, 0, N),
    P = ifelse(P < rho_threshold & P != 0, 0, P),
    qnp = ifelse(is.na(P) | is.na(N), NA, qnp),
    )

#Ok, let's select only the consistent ones.
filtered_scenar$run <- filtered_scenar %>%
  compute_occurences(.) %>%
  .$run %>%
  gather(clustering, value, N:cveg) %>%
  group_by(u, del, clustering) %>%
  summarise(value = mean(value, na.rm = TRUE)) %>%
  spread(clustering, value)

c1 <- plot_diagram(filtered_scenar, param = c(x = "del", y = "u"), fill = "cveg") +
  theme_alain() + #Need to remove inconsistent points
  xylabs(x = "del", y = "u") +
  scale_fill_temperature(name = "Clustering") 

```

```{r state_diagram}
filtered_scenar <- occurences
# status var is FALSE (is_run_normal) bc some qnn, qnp, etc... are NaN when P
# and N are absent. We will fix this to not have warning state in the state
#diagram:
filtered_scenar$run <- consistence %>%
  unnest() %>%
  mutate(
    N = ifelse(N < rho_threshold & N != 0, 0, N),
    P = ifelse(P < rho_threshold & P != 0, 0, P)
    ) %>% 
  gather(neighbor, value, qnn:qpp) %>%
  mutate(status = replace(value = NaN, TRUE, FALSE)) %>%
  spread(neighbor, value)

states <- compute_states(filtered_scenar, warning_as_desert = FALSE, threshold =
  .001)
states$run %<>% group_by(u, del) %>% # Get the most frequent state 
  summarise(state = names(sort(table(state),decreasing=TRUE)[1])) %>%
    left_join(consistence) %>% select(-data) %>% ungroup() %>%
    mutate(state = replace(state, consistence == FALSE, "unknown"),
      state = as.factor(state))

state_u <- plot_diagram(states, param = c(x = "del", y = "u")) +
  xylabs(x = "del", y = "u") +
  theme_alain()
legend_state <- get_legend(state_u)

state_u  <- state_u + theme(legend.position = "none")

```
```{r refined clustering plot}
# Put NaN to points which are not
clust_data <- ungroup(c1$data) %>%
  left_join(states$run) %>%
  gather(clust_type, clustering, cveg, cnp) %>% 
  mutate(clustering = replace(clustering, state %in% "nurse", NaN))

clust_scenar <- filtered_scenar
clust_scenar$run <- clust_data
## 

clust_u <- clust_data %>%
  group_by(clust_type) %>%
  nest() %>%
  mutate(
    plot_diagram = map(data, function(x) {
      ggplot2::ggplot(x,
      aes(x = del, y = u, fill = clustering)) +
    ggplot2::geom_raster() +
    theme_alain() +
    xylabs(x = "del", y = "u") +
    scale_fill_temperature(name = "Clustering", limits = c(2, 4.5))
}) 
  )

plot_grid(plotlist = clust_u$plot_diagram)



```

```{r q_np and indirect facilitation}
clust_np <- clust_scenar 
clust_np$run <- spread(clust_scenar$run, clust_type, clustering) %>%
  gather(var, values, qnp, N, qpn, P) %>%
  mutate(values = replace(values, state %in% c("unknown","desert", "nurse"), NaN)) %>%
  spread(var, values)

qpn_u <- plot_diagram(clust_np, param = c(x = "del", y = "u"), fill =
  "qpn") + 
  theme_alain() +
  xylabs(x = "del", y = "u") + # Replace tempature by yellow/red etc... add::
  # limits arg 
  scale_fill_temperature(name = "Average # of \n protegee neighbors \n for nurse cells", limits = c(0,2))
legend_qpn <- get_legend(qpn_u)

interp_qpn_u <- interp_contour(clust = clust_np$run, x = del, y = u, z = qpn, nb_pts = 30)

brks_q <- c(.25, .75, 1.25, 1.5)
contour_qpn_u <- qpn_u +
  draw_contour(interp_qpn_u, x = x, y = y, z = qpn, colour = "black", breaks = brks_q) 

p_qpn_u <- direct.label(contour_qpn_u, list("bottom.pieces",
      box.color = NA, fill = "transparent", colour = "black"))
```

```{r numbers for the paper}
clust_np$run %>%
  summarise(
    max = max(qpn, na.rm = TRUE),
    std = sd(qpn, na.rm = TRUE),
    min = min(qpn, na.rm = TRUE)
    )
```

## Relating to dispersal and direct facilitation


```{r}
# May be set up a function to analyze cellular automata (arg: rho_threshold,
# consistency_threshold)
data("direct_facilitation_dispersal_ca")
clust_ca <- direct_facilitation_dispersal_ca

##Options 
rho_threshold <- .01

##
clust_ca$run <- tibble::as.tibble(clust_ca$run) 
clust_ca$run <- arrange(clust_ca$run, f, del, rep)
occurences <- clust_ca

# Which simulation is good 
consistence <- occurences$run %>%
  group_by(f, del) %>%
  nest() %>%
  mutate(consistence = map_lgl(data, check_consistency, threshold = rho_threshold))

# Keep the good values
filtered_scenar <- occurences
filtered_scenar$run <- unnest(consistence) 
filtered_scenar$run %<>%
  mutate(
    N = ifelse(N < rho_threshold & N != 0, 0, N),
    P = ifelse(P < rho_threshold & P != 0, 0, P),
    qnp = ifelse(is.na(P) | is.na(N), NA, qnp),
    )

#Ok, let's select only the consistent ones.
filtered_scenar$run <- filtered_scenar %>%
  compute_occurences(.) %>%
  .$run %>%
  gather(clustering, value, N:cveg) %>%
  group_by(f, del, clustering) %>%
  summarise(value = mean(value, na.rm = TRUE)) %>%
  spread(clustering, value)

cveg_test <- plot_diagram(filtered_scenar, param = c(x = "del", y = "f"), fill =
  "cveg") + # We have to remove inconsistent runs    
  theme_alain() +
  xylabs(x = "del", y = "f") +
  scale_fill_temperature(name = "Clustering")
```

```{r}
filtered_scenar <- occurences
# status var is FALSE (is_run_normal) bc some qnn, qnp, etc... are NaN when P
# and N are absent. We will fix this to not have warning state in the state
#diagram:
filtered_scenar$run <- consistence %>%
  unnest() %>%
  mutate(
    N = ifelse(N < rho_threshold & N != 0, 0, N),
    P = ifelse(P < rho_threshold & P != 0, 0, P)
    ) %>% 
  gather(neighbor, value, qnn:qpp) %>%
  mutate(status = replace(value = NaN, TRUE, FALSE)) %>%
  spread(neighbor, value)

states <- compute_states(filtered_scenar, warning_as_desert = FALSE, threshold =
  .001)
states$run %<>% group_by(f, del) %>% # Get the most frequent state 
  summarise(state = names(sort(table(state),decreasing=TRUE)[1])) %>%
    left_join(consistence) %>% select(-data) %>% ungroup() %>%
    mutate(state = replace(state, consistence == FALSE, "unknown"),
      state = as.factor(state))

state_f <- plot_diagram(states, param = c(x = "del", y = "f")) +
  xylabs(x = "del", y = "f") +
  theme_alain() +
  theme(legend.position = "none")


```
```{r clustering_refined_ca}
# Put NaN to points which are not coexistence
clust_data <- ungroup(cveg_test$data) %>%
  left_join(states$run) %>%
  gather(clust_type, clustering, cveg, cnp) %>%
  mutate(clustering = replace(clustering, state %in% c("unknown","desert", "nurse"), NaN))

clust_scenar <- filtered_scenar
clust_scenar$run <- clust_data

clust_f <- plot_clustering_contour(clust_data, fac = f)


plot_grid(plotlist = clust_f$plot_diagram)

```

```{r qnp_f}
clust_np <- clust_scenar 
clust_np$run <- spread(clust_scenar$run, clust_type, clustering) %>%
  gather(var, values, qnp, N, qpn, P) %>%
  mutate(values = replace(values, state %in% c("unknown","desert", "nurse"), NaN)) %>%
  spread(var, values)

qpn_f <- plot_diagram(clust_np, param = c(x = "del", y = "f"), fill =
  "qpn") + 
  theme_alain() +
  xylabs(x = "del", y = "f") +
  scale_fill_temperature(name = "Average # of \n protegee neighbors \n for nurse cells", limits = c(0,2)) 
```
```{r add_contour}

interp_qpn_f <- interp_contour(clust_np$run, x = del, y = f, z = qpn, nb_pts = 30)

contour_qpn_f <- qpn_f +
  draw_contour(interp_qpn_f, x = x, y = y, z = qpn, colour = "black", breaks = brks_q) 

p_qpn_f <- direct.label(contour_qpn_f, list("bottom.pieces",
      box.color = NA, fill = "transparent", colour = "black"))

```

```{r numbers for the paper 2}
clust_np$run %>%
  summarise(
    max = max(qpn, na.rm = TRUE),
    std = sd(qpn, na.rm = TRUE),
    min = min(qpn, na.rm = TRUE)
    )
ggplot(clust_np$run, aes(y = qpn, x = del)) +
  geom_point()
```

# Clustering plot  

```{r clustering plot}

# Get legend
legend_clust <- get_legend(clust_u[1,]$plot_diagram[[1]]) 
legend_qpn <- get_legend(qpn_u) 
legend_state <- get_legend(state_f)

state_u
clust_u
p_qpn_u
state_f
clust_f
p_qpn_f

# Remove x axis
states <- map(list(state_u, state_f), rm_x_axis)
clust_f %<>% mutate(plot_diagram = map(plot_diagram, rm_x_axis))
clust_u %<>% mutate(plot_diagram = map(plot_diagram, rm_x_axis))

# Left column
list_of_plot <- list(states[[1]], clust_u[1, ]$plot_diagram[[1]],
  clust_u[2, ]$plot_diagram[[1]], p_qpn_u)
left_col <- plot_grid(plotlist = list_of_plot)
left_col

# Right column
list_of_plot <- list(states[[2]], clust_f$plot_diagram[[1]], p_qpn_f)
right_col <- plot_grid(plotlist = list_of_plot)
right_col

# Legend col
legend_col <- plot_grid(legend_state, legend_clust, legend_qpn)
legend_col


clustering_plot <- plot_grid(
  left_col,
  right_col,
  legend_col,
  ncol = 3,
  rel_width = c(1, 1, .5)
  )
clustering_plot

save_plot("~/Documents/thesis/papers/indirect_facilitation_dryland_stability/fig/clustering.pdf",
  clustering_plot,
  base_width = 174/25.4,
  base_height = 9,
  nrow = 1)
```

